# Generated by Django 3.0.8 on 2020-07-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Binary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitquery',
            name='count',
        ),
        migrations.AddField(
            model_name='gitquery',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
