# Generated by Django 3.0.8 on 2020-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Binary', '0002_auto_20200722_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitquery',
            name='number',
        ),
        migrations.AddField(
            model_name='gitquery',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gitquery',
            name='repo_count',
            field=models.IntegerField(default=0),
        ),
    ]
