# Generated by Django 3.0.8 on 2020-07-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Binary', '0003_auto_20200722_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitquery',
            name='folo_count',
            field=models.IntegerField(default=0),
        ),
    ]
